[root6] Avoid using unnecessary typedefs for TDataSet (#483)
The typedefs aliasing St_DataSet to TDataSet are not required. This
prevents us from running some nightly tests which load DB tables which
utilize this alias.

Fix error: unknown type name 'St_DataSet' in ROOT6 tests

```
LoadTable: .L /star-sw/StarDb/tpc/tsspars/tsspar.y2019.C
In file included from input_line_851:1:
/star-sw/StarDb/tpc/tsspars/tsspar.y2019.C:3:1: error: unknown type name 'St_DataSet'
St_DataSet *CreateTable() {
^
/star-sw/StarDb/tpc/tsspars/tsspar.y2019.C:57:10: error: use of undeclared identifier 'St_DataSet'
 return (St_DataSet *)tableSet;
         ^
/star-sw/StarDb/tpc/tsspars/tsspar.y2019.C:57:22: error: expected expression
 return (St_DataSet *)tableSet;
                     ^
root4star: .sl79_gcc485/OBJ/StRoot/St_db_Maker/St_db_Maker.cxx:932: virtual TDataSet* St_db_Maker::LoadTable(TDataSet*): Assertion `!ee' failed.
sh: line 1:   133 Aborted                 (core dumped) MALLOC_CHECK_=3 root4star -b -q -l 'bfc.C(50, "pp2022,StiCA,BEmcChkStat,ftt,-picowrite,-hitfilt,-evout", "/star/rcf/test/daq/2022/040/23040001/st_fwd_23040001_raw_0000003.daq")'
Error: Process completed with exit code 134.
```