Remove StRoot/StEStructPool/TSP
The library does not link due to multiple definitions

```
g++ -O2 -g -falign-loops -falign-jumps -falign-functions -shared -Wl,-Bdynamic -o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/StEStructPoolTSP.so .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddExtraCandidates.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddTourCandidates.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AdjustCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AllocateStructures.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Ascent.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Best2OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Best3OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Best4OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Best5OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/BestKOptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Between.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Between_SL.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Between_SSL.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/BridgeGain.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/BuildKDTree.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/C.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/CandidateReport.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ChooseInitialTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Connect.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/CreateCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/CreateDelaunayCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/CreateQuadrantCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Delaunay.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Distance.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Distance_SPECIAL.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ERXT.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Excludable.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Exclude.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/FindTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Flip.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Flip_SL.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Flip_SSL.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Forbidden.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/FreeStructures.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Gain23.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/GenerateCandidates.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Genetic.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/GeoConversion.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/GetTime.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/GreedyTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Hashing.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Heap.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/IsCandidate.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/IsCommonEdge.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/KSwapKick.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKHmain.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LinKernighan.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Make2OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Make3OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Make4OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Make5OptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/MakeKOptMove.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/MergeBetterTourWithBestTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/MergeWithTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Minimum1TreeCost.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/MinimumSpanningTree.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/NormalizeNodeList.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/NormalizeSegmentList.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/OrderCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/PatchCycles.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/PrintParameters.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Random.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ReadCandidates.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ReadLine.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ReadParameters.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ReadPenalties.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ReadProblem.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/RecordBestTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/RecordBetterTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/RemoveFirstActive.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/ResetCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/RestoreTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SFCTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SegmentSize.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Sequence.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveDelaunaySubproblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveKMeansSubproblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveKarpSubproblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveRoheSubproblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveSFCSubproblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveSubproblem.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveSubproblemBorderProblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SolveTourSegmentSubproblems.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Statistics.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/StoreTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/SymmetrizeCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/TrimCandidateSet.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/WriteCandidates.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/WritePenalties.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/WriteTour.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/eprintf.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/fscanint.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/malloc.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/printff.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/qsort.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/StEStructTEventList.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/StarTSP.o .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/StEStructPoolTSP_Cint.o
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:195: multiple definition of `FirstNode'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:195: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:231: multiple definition of `MergeTourFiles'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:231: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:305: multiple definition of `BestSubsequentMove'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:305: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:305: multiple definition of `BacktrackMove'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:305: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:305: multiple definition of `BestMove'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:305: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: multiple definition of `c'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: multiple definition of `C'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: multiple definition of `D'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: first defined here
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/AddCandidate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: multiple definition of `Distance'; .sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/Activate.o:/star-sw/.sl79_gcc11/OBJ/StRoot/StEStructPool/TSP/SRC/LKH.h:304: first defined here
```