fix: include missing header TLine.h (#626)
These errors appear when building the code against ROOT6.24

```
.sl79_gcc11/OBJ/StRoot/StFgtPool/StFgtQaMakers/StFgtPedStatQA.cxx:434:18: error: invalid use of incomplete type 'class TLine'
  434 |             lineB->Draw();
      |                  ^~
In file included from .sl79_gcc11/OBJ/StRoot/StFgtPool/StFgtQaMakers/StFgtPedStatQA.cxx:84:
/opt/software/linux-scientific7-x86_64/gcc-11.2.1/root-6.24.06-vianfhcgeujnnnnhm7g6hhr3tnsiwfqt/include/TPaveText.h:19:7: note: forward declaration of 'class TLine'
   19 | class TLine;
      |       ^~~~~
```

See https://github.com/star-bnl/star-sw/pull/619 for details