cons: Add quadmath lib used by gfortran
```
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /opt/rh/devtoolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgfortran_nonshared.a(nonshared-trigd.o): undefined reference to symbol 'fmaq@@QUADMATH_1.0'
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: /lib64/libquadmath.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
cons: *** [.sl79_gcc11/OBJ/asps/rexe/root4star] Error 1
cons: errors constructing .sl79_gcc11/OBJ/asps/rexe/root4star
```