Include TString header to fix incomplete type error in StGmtGeom
Fixed build error caused by missing #include <TString.h> in StGmtGeom.h

```
In file included from .sl73_x8664_gcc485/OBJ/StRoot/StGmtUtil/geometry/StGmtGeom.cxx:12:0:
.sl73_x8664_gcc485/OBJ/StRoot/StGmtUtil/geometry/StGmtGeom.h:195:14: error: field 'signal' has incomplete type
      TString signal;   // label string
              ^
.sl73_x8664_gcc485/OBJ/StRoot/StGmtUtil/geometry/StGmtGeom.cxx:657:1: error: too many initializers for 'StGmtGeom::StGmtGeomData'
 };
 ^
```