Table: Remove dubious constructor for TTable::iterator
While interpreting the code in `Table/TTable.h` Cling complains about
unintialized member of type `std::vector<long>::iterator`:

```
LoadTable: .L /star-sw/StarDb/Geometry/tpc/tpcPadConfig.y2019.C
In file included from ./.sl79_gcc485/include/tables/St_tpcPadConfig_Table.h:5:
/opt/software/linux-scientific7-x86_64/gcc-4.8.5/root-6.16.00-osnvudkiguzfhdpqgy2krbqybjbqvith/include/TTable.h:188:10: error: constructor for 'TTable::iterator' must explicitly initialize the member 'fCurrentRow' which does not have a default constructor
         iterator(): fRowSize(0), fThisTable(0) {;}
         ^
/opt/software/linux-scientific7-x86_64/gcc-4.8.5/root-6.16.00-osnvudkiguzfhdpqgy2krbqybjbqvith/include/TTable.h:186:24: note: member is declared here
         vec_iterator  fCurrentRow;
```

C++ allows to leave class members uninitilized but it is also true that it does
not make much sense to have a default constructor for an iterator. It appears to
me that `TTable::iterator()` is not used anywhere in the code therefore, it
should be safe to get rid of it.