[root6] Include missing definitions when interpreting AgMLGeometry
Unlike `rootcint` `rootcling` needs to see explicit definitions of the types
used in an interpreted code.

```
LoadTable: .L /star-sw/StarDb/AgMLGeometry/Geometry.y2021a.C
In file included from input_line_732:1:
In file included from /star-sw/StarDb/AgMLGeometry/Geometry.y2021a.C:2:
/star-sw/StarDb/AgMLGeometry/CreateGeometry.h:10:8: error: use of undeclared identifier 'gGeoManager'
  if ( gGeoManager ) {
       ^
/star-sw/StarDb/AgMLGeometry/CreateGeometry.h:11:56: error: use of undeclared identifier 'gGeoManager'
    cout << "AgML geometry:  Existing TGeoManager " << gGeoManager->GetName()
                                                       ^
/star-sw/StarDb/AgMLGeometry/CreateGeometry.h:36:7: error: use of undeclared identifier 'gGeoManager'
      gGeoManager = 0;
      ^
/star-sw/StarDb/AgMLGeometry/CreateGeometry.h:38:7: error: incomplete type 'TGeoManager' named in nested name specifier
      TGeoManager::Import( filename );
      ^~~~~~~~~~~~~
```

We also hide the included code from the ROOT5 interpreter because it
utilizes C++11 features